Global:
  debug: false
  use_gpu: true
  epoch_num: 700
  BURN_UP_STEP: 14500
  MAX_SREP: 40600
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./domain/domain_output/det_r50_icdar13_td_500epochs_total/
  save_epoch_step: 100
  eval_batch_step:
  - 0
  - 400
  cal_metric_during_train: false
  pretrained_model: ./pretrain_models/ResNet50_dcn_asf_synthtext_pretrained
  checkpoints: 
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db5/predicts_db.txt
Architecture:
  model_type: det
  algorithm: DB++
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
    dcn_stage: [False, True, True, True]
  Neck:
    name: DBFPN
    out_channels: 256
    use_asf: True
  Head:
    name: DBHead
    k: 50
  Aug: true
  Pseudo label: true
  DB Imgage alignment: true
  DB Instance alignment: true
  Consistency regularization: true
Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: BCELoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: DecayLearningRate
    learning_rate: 0.007
    epochs: 1000
    factor: 0.9
    end_lr: 0
  weight_decay: 0.0001
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.5
  max_candidates: 1000
  unclip_ratio: 1.5
  det_box_type: 'quad' # 'quad' or 'poly'
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2013/Text Localization/                                                                           
    label_file_list:                                                                                              
    - ./train_data/icdar2013/Text Localization/test_icdar2013_label.txt                                                         
    - ./train_data/icdar2013/Text Localization/train_icdar2013_label.txt                                                                  
    ratio_list:                                                                                                 
    - 1.0                                                                                                       
    - 1.0 
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.2
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 640
        - 640
        max_tries: 10
        keep_ratio: true
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - source_StrongAugment: null
    - NormalizeImage_strong:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage_strong: null
    - KeepKeys:
        keep_keys:
        - strong_image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 8
    num_workers: 2
    use_shared_memory: true
Target:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/TD_TR
    label_file_list:
    - ./train_data/TD_TR/TD500/train_gt_labels.txt
    - ./train_data/TD_TR/TR400/gt_labels.txt
    ratio_list:                                                                                                 
    - 1.0                                                                                                       
    - 0.75 
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.2
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 640
        - 640
        max_tries: 10
        keep_ratio: true
    - target_StrongAugment: null
    - NormalizeImage_strong:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage_strong: null
    - KeepKeys:
        keep_keys:
        - image
        - strong_image
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 8
    num_workers: 2
    use_shared_memory: True
Eval:
  dataset:
    name: SimpleDataSet 
    data_dir: ./train_data/TD_TR
    label_file_list:
    - ./train_data/TD_TR/TD500/test_gt_labels.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest:
        image_shape:
        - 768
        - 768
        keep_ratio: True
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: False
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null
