Global:
  debug: false
  use_gpu: true
  epoch_num: 700
  BURN_UP_STEP: 14500
  MAX_SREP: 40600
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./domain_output/det_r18_east_icdar13_mp_aug_pseduo_img/
  save_epoch_step: 200
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 400]
  cal_metric_during_train: False
  pretrained_model:  ./pretrain_models/best_accuracy
  # ./pretrain_models/ResNet18_vd_pretrained
  checkpoints: ./pretrain_models/best_accuracy
  save_inference_dir:
  use_visualdl: False
  infer_img: 
  save_res_path: ./output/det_east/predicts_east.txt
Architecture:
  model_type: det
  algorithm: EAST
  Transform:
  Backbone:
    name: ResNet_vd
    layers: 18
  # Backbone:
  #   name: ResNet
  #   layers: 50
  #   dcn_stage: [False, True, True, True]
  Neck:
    name: EASTFPN
    model_name: large
  Head:
    name: EASTHead
    model_name: large
  Aug: true
  Pseudo label: true
  EAST Imgage alignment: true
  EAST Instance alignment: false
  Consistency regularization: false
Loss:
  name: EASTLoss
  
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
  #  name: Cosine
    learning_rate: 0.001
  #  warmup_epoch: 0
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: EASTPostProcess
  score_thresh: 0.8
  cover_thresh: 0.1
  nms_thresh: 0.2

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2013/Text Localization/                                                                       
    label_file_list:                                                                                            
    - ./train_data/icdar2013/Text Localization/train_icdar2013_label.txt      
    - ./train_data/icdar2013/Text Localization/test_icdar2013_label.txt                                            
    ratio_list:                                                                                                 
    - 1.0 
    - 1.0 
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      # - StrongAugment_inplace: null
      # - source_StrongAugment: null
      # - IaaAugment:  # add add
      #     augmenter_args:
      #     - type: Fliplr
      #       args:
      #         p: 0.2
      #     - type: Affine
      #       args:
      #         rotate:
      #         - -5
      #         - 5
          # - type: Resize
          #   args:
          #     size:
          #     - 0.9
          #     - 1.1
      - EASTProcessTrain:
          image_shape: [512, 512]
          background_ratio: 0.125
          min_crop_side_ratio: 0.1
          min_text_size: 10
      - KeepKeys:
          keep_keys: ['image', 'score_map', 'geo_map', 'training_mask'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 8
    num_workers: 4
Target:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/mp                                                                       
    label_file_list:                                                                                            
    - ./train_data/mp/train_label.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      # - targetAugment_inplace: null
      # - target_StrongAugment: null
      # - IaaAugment:  # add add
      #     augmenter_args:
      #     - type: Fliplr
      #       args:
      #         p: 0.2
      #     - type: Affine
      #       args:
      #         rotate:
      #         - -5
      #         - 5
          # - type: Resize
          #   args:
          #     size:
          #     - 0.9
          #     - 1.1
      - EASTProcessTrain:
          image_shape: [512, 512]
          background_ratio: 0.125
          min_crop_side_ratio: 0.1
          min_text_size: 10
      - KeepKeys:
          keep_keys: ['image'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 8
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/mp
    label_file_list:
    - ./train_data/mp/val_label.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
          image_shape:
            - 736
            - 736
          # limit_side_len: 2400
          # limit_type: max
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2